### ISSUE TITLE
Can't run phpunit because of wrong composer dependencies

### ISSUE THREAD

**Issue by simonschaufi** [helhum/ext_scaffold#10]
I've just tried to setup a proper testing environment with this extension as base but failed because of this reason:

In this line https://github.com/helhum/ext_scaffold/blob/master/composer.json#L24 you require `typo3/cms-core` only which just installes the core extension in `.Build/Web/typo3/sysext/core`

When I make the following request, I get an error: 
```
TYPO3_PATH_WEB=$PWD/.Build/Web TYPO3_PATH_ROOT=$PWD/.Build/Web .Build/bin/phpunit --colors -c .Build/vendor/nimut/testing-framework/res/Configuration/UnitTests.xml Tests/Unit

Unable to determine path to entry script. Please check your path or set an environment variable 'TYPO3_PATH_ROOT' to your root path.
```
because of this line: https://github.com/Nimut/testing-framework/blob/master/src/TestingFramework/Bootstrap/AbstractBootstrap.php#L138-L143 which looks for `.Build/Web/typo3/index.php` which does **not** exist in my case.

Changing my require line to `typo3/cms` fixes the problem.

PS: I have even tried it with THIS extension and the tests are not working atm.

**Comment by helhum** [comment]
> Changing my require line to typo3/cms fixes the problem.

Please, don't add `typo3/cms` as requirement for your extensions. This isn't really correct and it will make your extension to not be compatible with typo3 for composer install in the future.

instead run composer require for testing: https://github.com/helhum/ext_scaffold/blob/master/.travis.yml#L49

**Comment by helhum** [comment]
but yeah, this template needs an update here, especially for it to work with TYPO3 9

**Comment by simonschaufi** [comment]
does it work for you with TYPO3 8?
