### ISSUE TITLE
Test suite doesn't match autoloading

### ISSUE THREAD

**Issue by TrueType** [helhum/ext_scaffold#4]
Hi Helmut,
thanks for putting up this example.
The composer.json loads tests classes only for core and fluid tests. So the example commands you name do not work. They start tests without proper classes loaded. E.g. dbal tests. 
If the aim is to have the starter run a view tests of TYPO3, quickly, a command to only run units tests of the sysext/core may be a way to go.
Henri

**Comment by helhum** [comment]
> So the example commands you name do not work

Which commands do not work?

> They start tests without proper classes loaded. E.g. dbal tests. 

Nope! Please be aware that backslashes at the end of the line mean, that the line break is for formatting only, the command is in fact in one line.

```
TYPO3_PATH_WEB=$PWD/.Build/Web \
\
.Build/bin/phpunit --colors -c \
  .Build/vendor/typo3/cms/typo3/sysext/core/Build/UnitTests.xml \
  Tests/Unit
```

Means (in one line)

`TYPO3_PATH_WEB=$PWD/.Build/Web .Build/bin/phpunit --colors -c   .Build/vendor/typo3/cms/typo3/sysext/core/Build/UnitTests.xml Tests/Unit`

> dbal tests

This extention is meant to meant as boilerplate to execute tests in your own extensions, not tests of the TYPO3 core. These can be easily executed by cloning the core repo, and doing composer install there.

> If the aim is to have the starter run a view tests of TYPO3

This is not the goal of this example. The goal is to provide a kickstart for extension developers to test their extensions, including integration of Travis

**Comment by TrueType** [comment]
Please take a look into the core/Build/UnitTests.xml. It is not only a phpunit configuration file, but contains the testsuites for all TYPO3 unit tests. Such configuration is official - https://phpunit.de/manual/current/en/phpunit-book.html#organizing-tests.xml-configuration

> PHPUnit's XML configuration file (Appendix C) can also be used to compose a test suite.

But whatever. I got that with the boilerplate. I want to build an important extension. I researched for an economics project and built TTD prototypes with simpletest and CakePHP 1.1. Wondering how I can port this app to TYPO3. Thanks for the help.

**Comment by helhum** [comment]
> Please take a look into the core/Build/UnitTests.xml. It is not only a phpunit configuration file, but contains the testsuites for all TYPO3 unit tests

I know that, I created that file :). But the configuration about test suits is ignored if you specify a directory like I did in the example :)

But you're right. It might be confusing for newbees if the directory is skipped (on purpose or by accident).

> Wondering how I can port this app to TYPO3

Sounds nice.

**Comment by TrueType** [comment]
Hey Helmut,
thanks for your patience. I really appreciate that. And you're right, of course, with the following a folder. That it overwrites the configuration suites. I'm new to PHPunit. And I wanted to run the TYPO3 unit tests... why I probably took the folder away.

You may still miss a "&&" in your command. The "export". Its two commands, or?

> Sounds nice.

Thx. Perhaps two more words. Here at the end of a closed issue. For this project of mine I spent 10 years of research. I finished last year with a economical theory on group decision making. What sounds boring. But after all its the answer on what political processes and democracy are all about. With my app I want to build a platform for a new kind of political party offering continuous voting and economically efficient decision making. .... What I want to say: It is hard to - with a full time job and wife and kids and so - to save the world in the spare time left. :) And. If you ever an interest in the things I mentioned. If all major work in TYPO3 is done. Let me know. There is some important work to be done.
